use_frameworks!

platform :ios, '9.0'

target 'BlueToothPrintAPI_Example' do
  pod 'BlueToothPrintAPI', :path => '../'

  target 'BlueToothPrintAPI_Tests' do
    inherit! :search_paths

    
  end
end
